package model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 02 23:26:00 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HomeOfficeWeekWiseDeptVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HomeOfficeWeekWiseDeptVOImpl() {
    }
}
