package model.views;


import java.sql.SQLException;

import model.services.AppModuleImpl;

import oracle.adf.model.BindingContext;
import oracle.adf.model.binding.DCBindingContainer;
import oracle.adf.model.binding.DCDataControl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 23 10:11:11 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HomeOfficeWeekListVORowImpl extends ViewRowImpl {


   

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        WeekId {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getWeekId();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setWeekId((Number)value);
            }
        }
        ,
        StartDate {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getStartDate();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setStartDate((Date)value);
            }
        }
        ,
        EndDate {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getEndDate();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setEndDate((Date)value);
            }
        }
        ,
        WeekRange {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getWeekRange();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setWeekRange((String)value);
            }
        }
        ,
        IsoWeekNumber {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getIsoWeekNumber();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setIsoWeekNumber((String)value);
            }
        }
        ,
        WeekOfYear {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getWeekOfYear();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setWeekOfYear((String)value);
            }
        }
        ,
        D1OfficeCount {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getD1OfficeCount();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setD1OfficeCount((Number)value);
            }
        }
        ,
        D2OfficeCount {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getD2OfficeCount();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setD2OfficeCount((Number)value);
            }
        }
        ,
        D3OfficeCount {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getD3OfficeCount();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setD3OfficeCount((Number)value);
            }
        }
        ,
        D4OfficeCount {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getD4OfficeCount();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setD4OfficeCount((Number)value);
            }
        }
        ,
        D5OfficeCount {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getD5OfficeCount();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setD5OfficeCount((Number)value);
            }
        }
        ,
        D6OfficeCount {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getD6OfficeCount();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setD6OfficeCount((Number)value);
            }
        }
        ,
        WeekNo {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getWeekNo();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setWeekNo((String)value);
            }
        }
        ,
        TotalEmployee {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getTotalEmployee();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setTotalEmployee((Number)value);
            }
        }
        ,
        D1OfficePercentage {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getD1OfficePercentage();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setD1OfficePercentage((Number)value);
            }
        }
        ,
        D2OfficePercentage {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getD2OfficePercentage();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setD2OfficePercentage((Number)value);
            }
        }
        ,
        D3OfficePercentage {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getD3OfficePercentage();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setD3OfficePercentage((Number)value);
            }
        }
        ,
        D4OfficePercentage {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getD4OfficePercentage();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setD4OfficePercentage((Number)value);
            }
        }
        ,
        D5OfficePercentage {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getD5OfficePercentage();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setD5OfficePercentage((Number)value);
            }
        }
        ,
        D6OfficePercentage {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getD6OfficePercentage();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setD6OfficePercentage((Number)value);
            }
        }
        ,
        EmpHomeOfficeWeekScVO {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getEmpHomeOfficeWeekScVO();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        HomeOfficeWeekWiseDeptVO {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getHomeOfficeWeekWiseDeptVO();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WeekNoLOV1 {
            public Object get(HomeOfficeWeekListVORowImpl obj) {
                return obj.getWeekNoLOV1();
            }

            public void put(HomeOfficeWeekListVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(HomeOfficeWeekListVORowImpl object);

        public abstract void put(HomeOfficeWeekListVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public AppModuleImpl getAppModuleImpl() {
    DCBindingContainer bindingContainer =
     (DCBindingContainer)BindingContext.getCurrent().getCurrentBindingsEntry();
    //BindingContext bindingContext = BindingContext.getCurrent();
    DCDataControl dc =
     bindingContainer.findDataControl("AppModuleDataControl"); // Name of application module in datacontrolBinding.cpx
    AppModuleImpl appM = (AppModuleImpl)dc.getDataProvider();
    return appM;
    }


    public static final int WEEKID = AttributesEnum.WeekId.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int WEEKRANGE = AttributesEnum.WeekRange.index();
    public static final int ISOWEEKNUMBER = AttributesEnum.IsoWeekNumber.index();
    public static final int WEEKOFYEAR = AttributesEnum.WeekOfYear.index();
    public static final int D1OFFICECOUNT = AttributesEnum.D1OfficeCount.index();
    public static final int D2OFFICECOUNT = AttributesEnum.D2OfficeCount.index();
    public static final int D3OFFICECOUNT = AttributesEnum.D3OfficeCount.index();
    public static final int D4OFFICECOUNT = AttributesEnum.D4OfficeCount.index();
    public static final int D5OFFICECOUNT = AttributesEnum.D5OfficeCount.index();
    public static final int D6OFFICECOUNT = AttributesEnum.D6OfficeCount.index();
    public static final int WEEKNO = AttributesEnum.WeekNo.index();
    public static final int TOTALEMPLOYEE = AttributesEnum.TotalEmployee.index();
    public static final int D1OFFICEPERCENTAGE = AttributesEnum.D1OfficePercentage.index();
    public static final int D2OFFICEPERCENTAGE = AttributesEnum.D2OfficePercentage.index();
    public static final int D3OFFICEPERCENTAGE = AttributesEnum.D3OfficePercentage.index();
    public static final int D4OFFICEPERCENTAGE = AttributesEnum.D4OfficePercentage.index();
    public static final int D5OFFICEPERCENTAGE = AttributesEnum.D5OfficePercentage.index();
    public static final int D6OFFICEPERCENTAGE = AttributesEnum.D6OfficePercentage.index();
    public static final int EMPHOMEOFFICEWEEKSCVO = AttributesEnum.EmpHomeOfficeWeekScVO.index();
    public static final int HOMEOFFICEWEEKWISEDEPTVO = AttributesEnum.HomeOfficeWeekWiseDeptVO.index();
    public static final int WEEKNOLOV1 = AttributesEnum.WeekNoLOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public HomeOfficeWeekListVORowImpl() {
    }

    /**
     * Gets HomeOfficeWeekListEO entity object.
     * @return the HomeOfficeWeekListEO
     */
    public EntityImpl getHomeOfficeWeekListEO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for WEEK_ID using the alias name WeekId.
     * @return the WEEK_ID
     */
    public Number getWeekId() {
        return (Number) getAttributeInternal(WEEKID);
    }

    /**
     * Sets <code>value</code> as attribute value for WEEK_ID using the alias name WeekId.
     * @param value value to set the WEEK_ID
     */
    public void setWeekId(Number value) {
        setAttributeInternal(WEEKID, value);
    }

    /**
     * Gets the attribute value for START_DATE using the alias name StartDate.
     * @return the START_DATE
     */
    public Date getStartDate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
     * @param value value to set the START_DATE
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for END_DATE using the alias name EndDate.
     * @return the END_DATE
     */
    public Date getEndDate() {
        return (Date) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
     * @param value value to set the END_DATE
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WeekRange.
     * @return the WeekRange
     */
    public String getWeekRange() {
        return (String) getAttributeInternal(WEEKRANGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WeekRange.
     * @param value value to set the  WeekRange
     */
    public void setWeekRange(String value) {
        setAttributeInternal(WEEKRANGE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsoWeekNumber.
     * @return the IsoWeekNumber
     */
    public String getIsoWeekNumber() {
        return (String) getAttributeInternal(ISOWEEKNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsoWeekNumber.
     * @param value value to set the  IsoWeekNumber
     */
    public void setIsoWeekNumber(String value) {
        setAttributeInternal(ISOWEEKNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WeekOfYear.
     * @return the WeekOfYear
     */
    public String getWeekOfYear() {
        return (String) getAttributeInternal(WEEKOFYEAR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WeekOfYear.
     * @param value value to set the  WeekOfYear
     */
    public void setWeekOfYear(String value) {
        setAttributeInternal(WEEKOFYEAR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D1OfficeCount.
     * @return the D1OfficeCount
     */
    public Number getD1OfficeCount() {
        return getOfficeCountForAttr("D1");
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D1OfficeCount.
     * @param value value to set the  D1OfficeCount
     */
    public void setD1OfficeCount(Number value) {
        setAttributeInternal(D1OFFICECOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D2OfficeCount.
     * @return the D2OfficeCount
     */
    public Number getD2OfficeCount() {
        return getOfficeCountForAttr("D2");
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D2OfficeCount.
     * @param value value to set the  D2OfficeCount
     */
    public void setD2OfficeCount(Number value) {
        setAttributeInternal(D2OFFICECOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D3OfficeCount.
     * @return the D3OfficeCount
     */
    public Number getD3OfficeCount() {
        return getOfficeCountForAttr("D3");
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D3OfficeCount.
     * @param value value to set the  D3OfficeCount
     */
    public void setD3OfficeCount(Number value) {
        setAttributeInternal(D3OFFICECOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D4OfficeCount.
     * @return the D4OfficeCount
     */
    public Number getD4OfficeCount() {
       return getOfficeCountForAttr("D4");
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D4OfficeCount.
     * @param value value to set the  D4OfficeCount
     */
    public void setD4OfficeCount(Number value) {
        setAttributeInternal(D4OFFICECOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D5OfficeCount.
     * @return the D5OfficeCount
     */
    public Number getD5OfficeCount() {
        
      return  getOfficeCountForAttr("D5");
        
        
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D5OfficeCount.
     * @param value value to set the  D5OfficeCount
     */
    public void setD5OfficeCount(Number value) {
        setAttributeInternal(D5OFFICECOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D6OfficeCount.
     * @return the D6OfficeCount
     */
    public Number getD6OfficeCount() {
        
        
      return  getOfficeCountForAttr("D6");
      
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D6OfficeCount.
     * @param value value to set the  D6OfficeCount
     */
    public void setD6OfficeCount(Number value) {
        setAttributeInternal(D6OFFICECOUNT, value);
    }


    /**
     * Gets the attribute value for the calculated attribute WeekNo.
     * @return the WeekNo
     */
    public String getWeekNo() {
        return (String) getAttributeInternal(WEEKNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WeekNo.
     * @param value value to set the  WeekNo
     */
    public void setWeekNo(String value) {
        setAttributeInternal(WEEKNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalEmployee.
     * @return the TotalEmployee
     */
    public Number getTotalEmployee() {

        String deptartment =
            (String)getAppModuleImpl().getDepartmentVO1().getCurrentRow().getAttribute("Departments");
        // System.out.println(" Department vo departments :" + deptartment);


      //  RowSet rs = (RowSet)this.getEmpHomeOfficeWeekScVO();
        // System.out.println("it.getAllRowsInRange().length  " + it.getAllRowsInRange().length);
        // System.out.println("   rows.length  "+rows.length);

        Row[] rows ;
      // rows = rs.getFilteredRows("Dept",deptartment );
       
         rows= this.getAppModuleImpl().getEmpHomeOfficeWeekScVO1().getAllRowsInRange();
       
            return new Number(rows.length);
    


        }


    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalEmployee.
     * @param value value to set the  TotalEmployee
     */
    public void setTotalEmployee(Number value) {
        setAttributeInternal(TOTALEMPLOYEE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D1OfficePercentage.
     * @return the D1OfficePercentage
     */
    public Number getD1OfficePercentage() {
        
        
      return  getCoOfficePercentage(this.getD1OfficeCount());
      
        

       // return (Number) getAttributeInternal(D1OFFICEPERCENTAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D1OfficePercentage.
     * @param value value to set the  D1OfficePercentage
     */
    public void setD1OfficePercentage(Number value) {
        setAttributeInternal(D1OFFICEPERCENTAGE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D2OfficePercentage.
     * @return the D2OfficePercentage
     */
    public Number getD2OfficePercentage() {
        return getCoOfficePercentage(this.getD2OfficeCount()) ;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D2OfficePercentage.
     * @param value value to set the  D2OfficePercentage
     */
    public void setD2OfficePercentage(Number value) {
        setAttributeInternal(D2OFFICEPERCENTAGE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D3OfficePercentage.
     * @return the D3OfficePercentage
     */
    public Number getD3OfficePercentage() {
        return getCoOfficePercentage(this.getD3OfficeCount()) ;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D3OfficePercentage.
     * @param value value to set the  D3OfficePercentage
     */
    public void setD3OfficePercentage(Number value) {
        setAttributeInternal(D3OFFICEPERCENTAGE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D4OfficePercentage.
     * @return the D4OfficePercentage
     */
    public Number getD4OfficePercentage() {
        return getCoOfficePercentage(this.getD4OfficeCount()) ;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D4OfficePercentage.
     * @param value value to set the  D4OfficePercentage
     */
    public void setD4OfficePercentage(Number value) {
        setAttributeInternal(D4OFFICEPERCENTAGE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D5OfficePercentage.
     * @return the D5OfficePercentage
     */
    public Number getD5OfficePercentage() {
        return getCoOfficePercentage(this.getD5OfficeCount()) ;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D5OfficePercentage.
     * @param value value to set the  D5OfficePercentage
     */
    public void setD5OfficePercentage(Number value) {
        setAttributeInternal(D5OFFICEPERCENTAGE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D6OfficePercentage.
     * @return the D6OfficePercentage
     */
    public Number getD6OfficePercentage() {
        return getCoOfficePercentage(this.getD6OfficeCount()) ;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D6OfficePercentage.
     * @param value value to set the  D6OfficePercentage
     */
    public void setD6OfficePercentage(Number value) {
        setAttributeInternal(D6OFFICEPERCENTAGE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EmpHomeOfficeWeekScVO.
     */
    public RowIterator getEmpHomeOfficeWeekScVO() {
        return (RowIterator)getAttributeInternal(EMPHOMEOFFICEWEEKSCVO);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HomeOfficeWeekWiseDeptVO.
     */
    public RowIterator getHomeOfficeWeekWiseDeptVO() {
        return (RowIterator)getAttributeInternal(HOMEOFFICEWEEKWISEDEPTVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> WeekNoLOV1.
     */
    public RowSet getWeekNoLOV1() {
        return (RowSet)getAttributeInternal(WEEKNOLOV1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
    
    
    private Number getOfficeCountForAttr(String string) {

        //System.out.println("===============   in getOfficeCountForAttr  for attr "+ string);
        String deptartment =
            (String)getAppModuleImpl().getDepartmentVO1().getCurrentRow().getAttribute("Departments");
       // System.out.println(" Department vo departments :" + deptartment);

       int i = 0, j = 0;
        RowSet rs = (RowSet)this.getEmpHomeOfficeWeekScVO();
       // System.out.println("===============   +rs.getAllRowsInRange().length "+rs.getAllRowsInRange().length);   
        Row[] rows ;
        
      // rows= rs.getFilteredRows("Dept",deptartment );
       
        String officeVal;
      //  System.out.println("===============   +rows.length "+rows.length);   
       
        rows = getAppModuleImpl().getEmpHomeOfficeWeekScVO1().getAllRowsInRange();
      //  System.out.println("=============   rows.length"+  rows.length);
        
        
        for(Row row:rows){
            
            try {
                officeVal = row.getAttribute(string).toString();
            } catch (Exception e) {
                // TODO: Add catch code
                officeVal ="";
            }
            
            if (officeVal.equals("CO Office")) {
                i++;
            }
        }
        return new Number(i);
 
    }
    
 
    private Number getCoOfficePercentage(Number coOfficeCount) {
        if(this.getTotalEmployee().isZero()){
            return new Number(0);
        }
        try {    
            
            return (Number)((coOfficeCount.div(this.getTotalEmployee())).mul(new Number(100))).floor();
        } catch (Exception e) {
            return new Number(0);
        }    
        
    }

}
