package model.views;

import model.entities.HomeOfficeWeekWiseDeptEOImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 02 23:26:00 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HomeOfficeWeekWiseDeptVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Department {
            public Object get(HomeOfficeWeekWiseDeptVORowImpl obj) {
                return obj.getDepartment();
            }

            public void put(HomeOfficeWeekWiseDeptVORowImpl obj,
                            Object value) {
                obj.setDepartment((String)value);
            }
        }
        ,
        SubmittedToHead {
            public Object get(HomeOfficeWeekWiseDeptVORowImpl obj) {
                return obj.getSubmittedToHead();
            }

            public void put(HomeOfficeWeekWiseDeptVORowImpl obj,
                            Object value) {
                obj.setSubmittedToHead((String)value);
            }
        }
        ,
        SubmittedToHr {
            public Object get(HomeOfficeWeekWiseDeptVORowImpl obj) {
                return obj.getSubmittedToHr();
            }

            public void put(HomeOfficeWeekWiseDeptVORowImpl obj,
                            Object value) {
                obj.setSubmittedToHr((String)value);
            }
        }
        ,
        WeekId {
            public Object get(HomeOfficeWeekWiseDeptVORowImpl obj) {
                return obj.getWeekId();
            }

            public void put(HomeOfficeWeekWiseDeptVORowImpl obj,
                            Object value) {
                obj.setWeekId((Number)value);
            }
        }
        ,
        FirstSubmissionToHr {
            public Object get(HomeOfficeWeekWiseDeptVORowImpl obj) {
                return obj.getFirstSubmissionToHr();
            }

            public void put(HomeOfficeWeekWiseDeptVORowImpl obj,
                            Object value) {
                obj.setFirstSubmissionToHr((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(HomeOfficeWeekWiseDeptVORowImpl object);

        public abstract void put(HomeOfficeWeekWiseDeptVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DEPARTMENT = AttributesEnum.Department.index();
    public static final int SUBMITTEDTOHEAD = AttributesEnum.SubmittedToHead.index();
    public static final int SUBMITTEDTOHR = AttributesEnum.SubmittedToHr.index();
    public static final int WEEKID = AttributesEnum.WeekId.index();
    public static final int FIRSTSUBMISSIONTOHR = AttributesEnum.FirstSubmissionToHr.index();

    /**
     * This is the default constructor (do not remove).
     */
    public HomeOfficeWeekWiseDeptVORowImpl() {
    }

    /**
     * Gets HomeOfficeWeekWiseDeptEO entity object.
     * @return the HomeOfficeWeekWiseDeptEO
     */
    public HomeOfficeWeekWiseDeptEOImpl getHomeOfficeWeekWiseDeptEO() {
        return (HomeOfficeWeekWiseDeptEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for DEPARTMENT using the alias name Department.
     * @return the DEPARTMENT
     */
    public String getDepartment() {
        return (String) getAttributeInternal(DEPARTMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT using the alias name Department.
     * @param value value to set the DEPARTMENT
     */
    public void setDepartment(String value) {
        setAttributeInternal(DEPARTMENT, value);
    }

    /**
     * Gets the attribute value for SUBMITTED_TO_HEAD using the alias name SubmittedToHead.
     * @return the SUBMITTED_TO_HEAD
     */
    public String getSubmittedToHead() {
        return (String) getAttributeInternal(SUBMITTEDTOHEAD);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMITTED_TO_HEAD using the alias name SubmittedToHead.
     * @param value value to set the SUBMITTED_TO_HEAD
     */
    public void setSubmittedToHead(String value) {
        setAttributeInternal(SUBMITTEDTOHEAD, value);
    }

    /**
     * Gets the attribute value for SUBMITTED_TO_HR using the alias name SubmittedToHr.
     * @return the SUBMITTED_TO_HR
     */
    public String getSubmittedToHr() {
        return (String) getAttributeInternal(SUBMITTEDTOHR);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMITTED_TO_HR using the alias name SubmittedToHr.
     * @param value value to set the SUBMITTED_TO_HR
     */
    public void setSubmittedToHr(String value) {
        setAttributeInternal(SUBMITTEDTOHR, value);
    }

    /**
     * Gets the attribute value for WEEK_ID using the alias name WeekId.
     * @return the WEEK_ID
     */
    public Number getWeekId() {
        return (Number) getAttributeInternal(WEEKID);
    }

    /**
     * Sets <code>value</code> as attribute value for WEEK_ID using the alias name WeekId.
     * @param value value to set the WEEK_ID
     */
    public void setWeekId(Number value) {
        setAttributeInternal(WEEKID, value);
    }

    /**
     * Gets the attribute value for FIRST_SUBMISSION_TO_HR using the alias name FirstSubmissionToHr.
     * @return the FIRST_SUBMISSION_TO_HR
     */
    public String getFirstSubmissionToHr() {
        return (String) getAttributeInternal(FIRSTSUBMISSIONTOHR);
    }

    /**
     * Sets <code>value</code> as attribute value for FIRST_SUBMISSION_TO_HR using the alias name FirstSubmissionToHr.
     * @param value value to set the FIRST_SUBMISSION_TO_HR
     */
    public void setFirstSubmissionToHr(String value) {
        setAttributeInternal(FIRSTSUBMISSIONTOHR, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
