package model.lov;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 19 15:24:27 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HomeOffice2LovRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HomeOffice {
            public Object get(HomeOffice2LovRowImpl obj) {
                return obj.getHomeOffice();
            }

            public void put(HomeOffice2LovRowImpl obj, Object value) {
                obj.setHomeOffice((String)value);
            }
        }
        ,
        Rankk {
            public Object get(HomeOffice2LovRowImpl obj) {
                return obj.getRankk();
            }

            public void put(HomeOffice2LovRowImpl obj, Object value) {
                obj.setRankk((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(HomeOffice2LovRowImpl object);

        public abstract void put(HomeOffice2LovRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HOMEOFFICE = AttributesEnum.HomeOffice.index();
    public static final int RANKK = AttributesEnum.Rankk.index();

    /**
     * This is the default constructor (do not remove).
     */
    public HomeOffice2LovRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute HomeOffice.
     * @return the HomeOffice
     */
    public String getHomeOffice() {
        return (String) getAttributeInternal(HOMEOFFICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HomeOffice.
     * @param value value to set the  HomeOffice
     */
    public void setHomeOffice(String value) {
        setAttributeInternal(HOMEOFFICE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Rankk.
     * @return the Rankk
     */
    public Number getRankk() {
        return (Number) getAttributeInternal(RANKK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Rankk.
     * @param value value to set the  Rankk
     */
    public void setRankk(Number value) {
        setAttributeInternal(RANKK, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
