package model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 19 15:24:27 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HomeOffice2LovImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HomeOffice2LovImpl() {
    }
}
